# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 1
  tensorboard_logdir: tb

checkpoint:
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: data2vec_uni_pretraining
  data: ???
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true
  labels: phn
  speech_data: train_860 # set "None" to disable speech data

dataset:
  num_workers: 1
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  validate_interval_updates: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 1
  ddp_backend: no_c10d

criterion:
  _name: data2vec_uni_criterion
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - loss_speech
    - loss_text
    - text_ema_decay

optimization:
  max_update: 400000
  lr: [0.0005]
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.03,0.9,0.07]

model:
  _name: data2vec_uni
  extractor_mode: layer_norm
  encoder_layerdrop: 0.05
  dropout_input: 0.0
  dropout_features: 0.0
  feature_grad_mult: 1.0
  encoder_embed_dim: 768

  mask_prob: 0.65
  mask_length: 10

  loss_beta: 0.25
  loss_scale: null

  instance_norm_target_layer: true
  average_top_k_layers: 8

  pos_conv_depth: 5
  conv_pos: 95

  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 30000
  ema_transformer_only: true
  ema_layers_only: true

  require_same_masks: true
  mask_dropout: 0

  speech_pretrained_model: true
  speech_model_path: ???
  
  ########## below are for text teacher ##########
  text_pretrained_model: true
  text_model_path: ???
  text_max_positions: 512

  text_head_layers: 2
  text_average_top_k_layers: 10
  text_layer_norm_target_layer: true
  text_loss_scale: 1
  text_ema_decay: 0.999
  text_ema_end_decay: 0.9999
  text_ema_anneal_end_step: 100000
  text_loss_beta: 4
  text_ema_transformer_layers_only: true

  text_transformer:
    dropout: 0.1
    attention_dropout: 0.1
    layernorm_embedding: true
    activation_fn: gelu
    no_scale_embedding: true
    max_source_positions: 512
    encoder:
      embed_dim: 768
      ffn_embed_dim: 3072
      layers: 12
      attention_heads: 12
      normalize_before: false
      learned_pos: true
      layerdrop: 0

  text_teacher: true
  text_init_transformer: false
  text_do_ema: true
  text_loss_alpha: 0.1